apiVersion: v1
kind: Service
metadata:
  name: skin-analysis-backend-service
spec:
  selector:
    app: skin-analysis-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
